#!/usr/bin/env bash
set -e

# Load default configuration values
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/setup.defaults"

TFVARS_FILE="terraform.tfvars"

echo "=== Proxy Infrastructure Setup ==="

# 1. AWS Region
read -p "Enter AWS Region [$DEFAULT_AWS_REGION]: " AWS_REGION
AWS_REGION=${AWS_REGION:-$DEFAULT_AWS_REGION}

# 2. Proxy Auth Token
if [ -n "$PROXY_AUTH_TOKEN" ]; then
  read -p "You have PROXY_AUTH_TOKEN set in your environment. Do you want to use it? (y/n) [y]: " USE_ENV_TOKEN
  USE_ENV_TOKEN=${USE_ENV_TOKEN:-y}
  if [[ "$USE_ENV_TOKEN" != "y" ]]; then
    PROXY_AUTH_TOKEN=$(openssl rand -hex 16)
  fi
else
  PROXY_AUTH_TOKEN=$(openssl rand -hex 16)
fi

# 3. Processor Port
read -p "Enter Processor Port [$DEFAULT_PROCESSOR_PORT]: " PROCESSOR_PORT
PROCESSOR_PORT=${PROCESSOR_PORT:-$DEFAULT_PROCESSOR_PORT}

# 4. VPC CIDR
read -p "Enter VPC CIDR block [$DEFAULT_VPC_CIDR]: " VPC_CIDR
VPC_CIDR=${VPC_CIDR:-$DEFAULT_VPC_CIDR}

# 5. instance type and AMI
read -p "Enter EC2 instance type for proxy processor [$DEFAULT_INSTANCE_TYPE]: " INSTANCE_TYPE
INSTANCE_TYPE=${INSTANCE_TYPE:-$DEFAULT_INSTANCE_TYPE}

read -p "Enter AMI ID for EC2 instances (e.g., Amazon Linux 2) [$DEFAULT_AMI_ID]: " AMI_ID
AMI_ID=${AMI_ID:-$DEFAULT_AMI_ID}

# Write the configuration to terraform.tfvars
cat <<EOF > "$TFVARS_FILE"
# Auto-generated by setup.sh
aws_region       = "$AWS_REGION"
proxy_auth_token = "$PROXY_AUTH_TOKEN"
processor_port   = $PROCESSOR_PORT
vpc_cidr         = "$VPC_CIDR"
EOF

echo ""
echo "Successfully generated $TFVARS_FILE"
echo "You can now run 'terraform init' followed by 'terraform plan'."